# Software Engineer: Kyeshav Chettiar 
# Company FXO - Adcorp 
# Configured and pushed onto the virtual machine for testing and evaluation for team members to use within the companies rules and regulations 
# v3.0.0.0 
# Docker Configured & new project directory has been created for this version on github at the following link: 

import os
import io
import qrcode
from fpdf import FPDF
from datetime import datetime

class ArrivalCertificate(FPDF):
    def header(self):
        # Altron/Transnet Branding Header
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'PORTGUARD CCMS v3 - ARRIVAL CERTIFICATE', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 5, 'Official Port of Durban Gate Entry Document', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        # Audit Trail Footer
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 10, f'Generated by PortGuard System | {timestamp} | Page {self.page_no()}', 0, 0, 'C')

def generate_container_pdf(container_data: dict, images: list):
    try:
        pdf = ArrivalCertificate()
        pdf.add_page()
        pdf.set_font("Arial", size=12)

        # 1. Container Info Section
        pdf.set_fill_color(240, 240, 240)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, f"Container Number: {container_data['container_no']}", 1, 1, 'L', fill=True)
        pdf.set_font("Arial", '', 11)
        pdf.cell(0, 10, f"Status: {container_data['status']}", 1, 1, 'L')
        pdf.cell(0, 10, f"Arrival ID: {container_data['id']}", 1, 1, 'L')
        pdf.ln(5)

        # 2. QR Code Generation for Gate Scanning
        qr = qrcode.QRCode(version=1, box_size=10, border=4)
        # Replace '192.168.1.100' with your actual computer IP!
        qr_data = f"http://192.168.1.36:8000/verify/{container_data['id']}"
        qr.add_data(qr_data)
        qr.make(fit=True)
        
        img_qr = qr.make_image(fill_color="black", back_color="white")
        
        # Use a BytesIO buffer to avoid physical file writes
        qr_buffer = io.BytesIO()
        img_qr.save(qr_buffer, "PNG") 
        qr_buffer.seek(0)

        # Place QR Code on PDF (Top Right)
        pdf.image(qr_buffer, x=165, y=25, w=30)
        
        # 3. Evidence Images Grid with Path Resolution
        pdf.ln(10)
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "Complete Photo Evidence (360 Inspection):", 0, 1)
        pdf.set_font("Arial", '', 8)

        # Get the absolute path to the project root
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

        for i, img in enumerate(images):
            # 2-column grid layout logic
            x_pos = 10 if (i % 2 == 0) else 110
            if i % 2 == 0 and i > 0:
                pdf.ln(55) 
                
            current_y = pdf.get_y()
            pdf.text(x_pos, current_y, f"Angle: {img.image_type.upper()}")
                
            # Construct and verify Absolute Path
            full_path = os.path.normpath(os.path.join(base_dir, img.file_path))

            if os.path.exists(full_path):
                pdf.image(full_path, x=x_pos, y=current_y + 2, w=90)
            else:
                pdf.set_xy(x_pos, current_y + 10)
                pdf.set_text_color(255, 0, 0)
                pdf.cell(90, 10, f"MISSING FILE: {img.image_type}", 1, 0, 'C')
                pdf.set_text_color(0, 0, 0)

        return pdf.output(dest='S')
            
    except Exception as e:
        print(f"CRITICAL PDF ERROR: {str(e)}")
        return None